name: EAS inject env vars
description: Inject environment variables into eas.json file
branding:
  icon: terminal
  color: gray-dark
inputs:
  eas_env:
    description: "EAS environment"
    required: true
  env_vars:
    description: "Environment variable key-value pairs"
    required: true
  eas_json_path:
    description: "Path to eas.json file"
    required: true

runs:
  using: composite
  steps:
    - id: load_env
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/inject-env.sh -i '${{ inputs.env_vars }}' -e ${{ inputs.eas_env }} -p ${{ inputs.eas_json_path }}
