name: Inject env
description: Injects env variables into eas.json file for eas submit
inputs:
  eas_env:
    description: "EAS environment"
    required: true
  env_vars:
    description: "Environment variable key-value pairs"
    required: true
  eas_json_path:
    description: "Path to EAS JSON file"
    required: true
runs:
  using: composite

  steps:
    - id: load_env
      shell: bash
      run: |
        ./inject-env.sh -i ${{ inputs.eas_env }} -e ${{ inputs.env_vars }} -j ${{ inputs.eas_json_path }}
        echo "Environment variables loaded into eas.json file"
